name: FIRST-JOB

# Controls when the workflow will run
on:
  push:
    

# A workflow run is made up of one or more jobs
jobs:
  Build:
     runs-on: ubuntu-latest
     steps:
      - name: checkout to git
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: firstjob
        run: echo "hello world"